(*
 * Rel Language Grammar Specification
 * Version: 0.1.0-draft
 * Format: Extended Backus-Naur Form (EBNF)
 *)

(* ===== TOP LEVEL ===== *)

program         = { statement } ;

statement       = query_def
                | entity_def
                | relation_def
                | type_alias
                | enum_def
                | import_stmt
                | module_def
                | migration_def
                | stream_def
                | transaction_def
                | version_directive ;

version_directive = "#!rel" , version_string , NEWLINE ;
version_string    = digit , "." , digit , { "." , digit } ;


(* ===== IMPORTS & MODULES ===== *)

import_stmt     = "import" , module_path , [ import_items ] ;
import_items    = "{" , IDENT , { "," , IDENT } , "}"
                | "as" , IDENT
                | ".*" ;
module_path     = IDENT , { "." , IDENT } ;

module_def      = "module" , IDENT , "{" , { statement } , "}" ;

namespace_def   = "namespace" , IDENT , "{" , { statement } , "}" ;


(* ===== QUERY DEFINITION ===== *)

query_def       = { annotation } , "query" , IDENT , [ params ] , "{" , pipeline , "}" ;
params          = "(" , [ param , { "," , param } ] , ")" ;
param           = IDENT , ":" , type_expr , [ "=" , expr ] ;

pipeline        = source_clause , { pipe_op , operator } ;
pipe_op         = "|>" ;
source_clause   = "from" , source_expr ;

source_expr     = nav_chain
                | query_call
                | subquery ;

nav_chain       = IDENT , { nav_op , IDENT } ;
query_call      = IDENT , "(" , [ arg_list ] , ")" ;
subquery        = "(" , pipeline , ")" ;

nav_op          = "->"    (* INNER JOIN / has-one / belongs-to *)
                | "-?>"   (* LEFT JOIN  / optional relation    *)
                | "<-"    (* reverse relation                  *)
                | "<->"   (* full outer join                   *)
                | "~>"    (* recursive / graph traversal       *)
                ;


(* ===== PIPELINE OPERATORS ===== *)

operator        = where_op
                | select_op
                | group_op
                | having_op
                | order_op
                | take_op
                | navigate_op
                | window_op
                | let_op
                | set_op
                | distinct_op
                | flatten_op
                | cursor_paginate_op
                | lock_op ;

where_op        = "where" , expr ;

select_op       = "select" , projection ;
projection      = field_access
                | struct_literal
                | "*" ;

group_op        = "group" , "by" , group_key , { "," , group_key } ;
group_key       = IDENT , ":" , field_access
                | field_access ;

having_op       = "having" , expr ;

order_op        = "order" , "by" , order_term , { "," , order_term } ;
order_term      = expr , [ "asc" | "desc" ] , [ "nulls" , ( "first" | "last" ) ] ;

take_op         = "take" , expr , [ "skip" , expr ] ;

navigate_op     = "navigate" , nav_expr , [ "as" , IDENT ] ;
nav_expr        = "." , IDENT , nav_op
                | IDENT , nav_op , IDENT ;

window_op       = "window" , "{" , window_field , { "," , window_field } , "}" ;
window_field    = IDENT , ":" , agg_call , "over" , "(" , window_spec , ")" ;
window_spec     = [ partition_clause ] , [ order_clause ] , [ frame_clause ] ;
partition_clause = "partition" , "by" , expr , { "," , expr } ;
order_clause    = "order" , "by" , order_term , { "," , order_term } ;
frame_clause    = ( "rows" | "range" ) , frame_bound , "to" , frame_bound ;
frame_bound     = "unbounded" , "preceding"
                | expr , "preceding"
                | "current" , "row"
                | expr , "following"
                | "unbounded" , "following" ;

let_op          = "let" , IDENT , "=" , expr ;

distinct_op     = "distinct" , [ "by" , expr , { "," , expr } ] ;

flatten_op      = "flatten" , [ "." , IDENT ] ;

cursor_paginate_op = "cursor_paginate" , "{" ,
                       "after" , ":" , expr , ","
                       "per_page" , ":" , expr ,
                     "}" ;

lock_op         = "lock" , "(" , "for" , ":" , ( "read" | "update" | "share" ) , ")" ;

set_op          = "set" , "{" , set_field , { "," , set_field } , "}" ;
set_field       = "." , IDENT , ":" , expr ;


(* ===== EXPRESSIONS ===== *)

expr            = or_expr ;
or_expr         = and_expr , { "or" , and_expr } ;
and_expr        = not_expr , { "and" , not_expr } ;
not_expr        = [ "not" ] , compare_expr ;
compare_expr    = add_expr , { compare_op , add_expr } ;
compare_op      = "==" | "!=" | "<" | "<=" | ">" | ">=" | "in" | "not" , "in" | "like" ;
add_expr        = mul_expr , { ( "+" | "-" | "++" ) , mul_expr } ;
mul_expr        = unary_expr , { ( "*" | "/" | "%" ) , unary_expr } ;
unary_expr      = [ "-" | "not" ] , postfix_expr ;
postfix_expr    = primary_expr , { postfix_op } ;
postfix_op      = "." , IDENT                    (* field access      *)
                | "?." , IDENT                   (* optional chaining *)
                | "(" , [ arg_list ] , ")"       (* function call     *)
                | "[" , expr , "]"               (* index access      *)
                | "??" , expr                    (* null coalescing   *)
                | "!"                            (* unwrap / assert   *)
                ;

primary_expr    = literal
                | field_access
                | struct_literal
                | list_literal
                | map_literal
                | call_expr
                | if_expr
                | match_expr
                | lambda_expr
                | "(" , expr , ")"
                | IDENT ;

field_access    = "." , IDENT , { "." , IDENT } ;

struct_literal  = "{" , [ struct_field , { "," , struct_field } ] , "}" ;
struct_field    = IDENT , ":" , expr
                | "." , IDENT           (* shorthand: .name = name: .name *)
                | "..." , expr ;         (* spread *)

list_literal    = "[" , [ expr , { "," , expr } ] , "]" ;

map_literal     = "Map" , "{" , [ map_entry , { "," , map_entry } ] , "}" ;
map_entry       = expr , ":" , expr ;

call_expr       = IDENT , "(" , [ arg_list ] , ")" ;
arg_list        = arg , { "," , arg } ;
arg             = [ IDENT , ":" ] , expr ;

if_expr         = "if" , expr , "then" , expr , "else" , expr ;

match_expr      = "match" , expr , "{" , match_arm , { match_arm } , "}" ;
match_arm       = pattern , "=>" , expr , "," ;
pattern         = "_"
                | literal
                | IDENT
                | IDENT , "(" , [ IDENT , { "," , IDENT } ] , ")"
                | "Some" , "(" , IDENT , ")"
                | "None" ;

lambda_expr     = "|" , [ lambda_params ] , "|" , expr ;
lambda_params   = IDENT , { "," , IDENT } ;

agg_call        = agg_func , "(" , [ agg_arg ] , ")" ;
agg_func        = "count" | "sum" | "avg" | "min" | "max"
                | "stddev" | "variance" | "median"
                | "collect" | "first" | "last"
                | "rank" | "dense_rank" | "row_number"
                | "lag" | "lead" | "nth_value" ;
agg_arg         = [ "distinct" ] , [ expr ] ;


(* ===== TYPE EXPRESSIONS ===== *)

type_expr       = base_type
                | option_type
                | list_type
                | set_type
                | map_type
                | tuple_type
                | union_type
                | struct_type
                | stream_type ;

base_type       = IDENT , [ "(" , INT , [ "," , INT ] , ")" ] ;
option_type     = type_expr , "?" ;
list_type       = "List" , "<" , type_expr , ">" ;
set_type        = "Set" , "<" , type_expr , ">" ;
map_type        = "Map" , "<" , type_expr , "," , type_expr , ">" ;
tuple_type      = "(" , type_expr , "," , type_expr , { "," , type_expr } , ")" ;
union_type      = type_expr , "|" , type_expr ;
struct_type     = "{" , type_field , { "," , type_field } , "}" ;
type_field      = IDENT , ":" , type_expr ;
stream_type     = "Stream" , "<" , type_expr , ">" ;


(* ===== ENTITY DEFINITION ===== *)

entity_def      = { annotation } , "entity" , IDENT , [ "extends" , IDENT ] , "{"
                    { field_def | entity_annotation }
                  "}" ;

field_def       = IDENT , ":" , type_expr , { annotation } ;

entity_annotation = "@index" , "(" , "[" , IDENT , { "," , IDENT } , "]" , ")"
                  | "@check" , "(" , expr , ")"
                  | "@shard" , "(" , shard_config , ")" ;

shard_config    = shard_option , { "," , shard_option } ;
shard_option    = "strategy" , ":" , ( "hash" | "range" | "list" )
                | "key" , ":" , field_access
                | "count" , ":" , INT
                | "replicas" , ":" , INT ;


(* ===== RELATION DEFINITION ===== *)

relation_def    = "relation" , IDENT , "." , IDENT ,
                  nav_op , IDENT , [ "?" ] ,
                  [ "via" , via_spec ] ,
                  [ "where" , expr ] ,
                  [ "order" , "by" , order_term , { "," , order_term } ] ;

via_spec        = IDENT                             (* foreign key field  *)
                | IDENT , "{" , via_field , { "," , via_field } , "}"  (* join table *)
                | "(" , IDENT , "," , IDENT , ")"  (* polymorphic        *)
                ;

via_field       = IDENT , ":" , IDENT , "->" , IDENT , "." , IDENT ;


(* ===== TYPE ALIASES ===== *)

type_alias      = "type" , IDENT , "=" , type_expr , { annotation } ;


(* ===== ENUM DEFINITION ===== *)

enum_def        = "enum" , IDENT , "{" , enum_variant , { enum_variant } , "}" ;
enum_variant    = IDENT , [ "=" , ( STRING | INT ) ] ;


(* ===== ANNOTATIONS ===== *)

annotation      = "@" , IDENT , [ "(" , annotation_args , ")" ] ;
annotation_args = annotation_arg , { "," , annotation_arg } ;
annotation_arg  = [ IDENT , ":" ] , annotation_value ;
annotation_value = expr | type_expr ;


(* ===== MIGRATION DEFINITION ===== *)

migration_def   = "migration" , IDENT , "{" ,
                    "version" , ":" , STRING , ","
                    [ "description" , ":" , STRING , "," ]
                    "up" , "{" , { ddl_stmt } , "}" ,
                    "down" , "{" , { ddl_stmt } , "}"
                  "}" ;

ddl_stmt        = alter_entity
                | add_index_stmt
                | drop_index_stmt ;

alter_entity    = "alter" , IDENT , "{" , { alter_field } , "}" ;
alter_field     = "add" , field_def
                | "drop" , IDENT
                | "rename" , IDENT , "to" , IDENT
                | "modify" , IDENT , ":" , type_expr ;

add_index_stmt  = "add_index" , IDENT , "." , IDENT ;
drop_index_stmt = "drop_index" , IDENT , "." , IDENT ;


(* ===== STREAM DEFINITION ===== *)

stream_def      = "stream" , IDENT , "from" , stream_source , "{" ,
                    "format" , ":" , ( "json" | "avro" | "protobuf" ) , ","
                    "schema" , ":" , ( type_expr | IDENT )
                  "}" ;

stream_source   = "kafka" , "(" , STRING , ")"
                | "kinesis" , "(" , STRING , ")"
                | "mqtt" , "(" , STRING , ")"
                | "http_sse" , "(" , STRING , ")" ;


(* ===== TRANSACTION DEFINITION ===== *)

transaction_def = "transaction" , IDENT , "{" ,
                    [ transaction_option , { "," , transaction_option } ]
                    "steps" , "{" , { tx_stmt } , "}"
                  "}" ;

transaction_option = "isolation" , ":" , isolation_level
                   | "timeout" , ":" , duration_lit
                   | "retry" , ":" , INT ;

isolation_level = "read_committed" | "repeatable_read" | "serializable" ;

tx_stmt         = let_stmt
                | insert_stmt
                | update_stmt
                | delete_stmt
                | guard_stmt
                | await_stmt
                | return_stmt ;

let_stmt        = "let" , IDENT , "=" , expr ;
insert_stmt     = "insert" , IDENT , struct_literal ;
update_stmt     = "update" , IDENT , "|>" , where_op , "|>" , set_op ;
delete_stmt     = "delete" , IDENT , "|>" , where_op ;
guard_stmt      = "guard" , expr , "else" , expr ;
await_stmt      = "await" , call_expr ;
return_stmt     = "return" , expr ;


(* ===== LITERALS ===== *)

literal         = INT
                | FLOAT
                | DECIMAL
                | STRING
                | BOOL
                | NULL
                | uuid_lit
                | duration_lit
                | date_lit
                | time_lit
                | timestamp_lit ;

INT             = digit , { digit } ;
FLOAT           = digit , { digit } , "." , digit , { digit } , [ exponent ] ;
DECIMAL         = digit , { digit } , "." , digit , { digit } , "m" ;
STRING          = '"' , { char } , '"' ;
BOOL            = "true" | "false" ;
NULL            = "None" ;
uuid_lit        = "UUID" , "(" , STRING , ")" ;
duration_lit    = INT , ( "ms" | "s" | "m" | "h" | "d" | "w" ) ;
date_lit        = "Date" , "(" , STRING , ")" ;
time_lit        = "Time" , "(" , STRING , ")" ;
timestamp_lit   = "Timestamp" , "(" , STRING , ")" ;

exponent        = ( "e" | "E" ) , [ "+" | "-" ] , digit , { digit } ;

IDENT           = letter , { letter | digit | "_" } ;
letter          = "A" | ... | "Z" | "a" | ... | "z" | "_" ;
digit           = "0" | ... | "9" ;
NEWLINE         = "\n" | "\r\n" ;

(* ===== COMMENTS ===== *)
(* Line comment:  -- this is a comment  *)
(* Block comment: /* this is a comment */ *)
